name: Test
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: Run linter and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Check i18n
        shell: bash
        run: |
          yarn i18n
          GIT_STATUS="$(git status --short --untracked-files locales)"
          if [ -n "$GIT_STATUS" ]; then
            echo "i18n files are not up to date. Commit them to fix."
            git diff
            exit 1
          fi

      - name: Test
        run: yarn test:coverage

      - name: Build
        run: yarn build
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install kinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install k8s and oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz

          sudo install oc /usr/local/bin/oc
          sudo install kubectl /usr/local/bin/kubectl
      - name: Install podman
        run: |
          curl -LO https://github.com/containers/podman/releases/download/v3.4.4/podman-remote-static.tar.gz
          tar -xvf podman-remote-static.tar.gz
          sudo install podman-remote-static /usr/local/bin/podman

          curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-1_amd64.deb
          sudo dpkg -i containernetworking-plugins_1.1.1+ds1-1_amd64.deb

      - name: Create Cluster
        run: |
          yarn create-cluster
          yarn login-cluster
      - name: Cypress run
        uses: cypress-io/github-action@v5.8.1
        with:
          start: yarn dev, yarn start-console
          wait-on: "http://localhost:9001"
          browser: chrome
          headed: false

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
